#!/usr/bin/env bash
# demo-blockage.sh — Demo the geo_blockage scenario: a continuously-covered
# GEO link (satellite always in view) that still drops intermittently as a
# vehicle passes through a tunnel, a cutting, or dense tree cover.
#
# Unlike a periodic pass, these drops are UNSCHEDULED and have NO lookahead:
# the app gets no advance notice, so it must detect the outage reactively
# (timeouts) and recover. Watch the poller: steady 200s while covered, then
# sudden "timeout" rows during a blockage, then recovery — with no warning.
#
# Usage:
#   ./scripts/demo-blockage.sh              # fast demo profile + poller + GUI
#   ./scripts/demo-blockage.sh --tui        # with live TUI dashboard
#   ./scripts/demo-blockage.sh --report out.json  # field-data JSON at session end
#   ./scripts/demo-blockage.sh --real       # realistic 300s profile (slow: first drop at 60s)
#   ./scripts/demo-blockage.sh --help
#
# By default this generates a short profile (30s cycle: covered, ~4s tunnel,
# covered, ~6s ridge) so drops appear within ~10s. Use --real to run the
# committed testdata/profiles/geo_blockage.yaml instead.
#
# macOS: ntnbox auto-reinvokes inside Docker; this builds the image for you.
# Linux: run with sudo (netns shaping needs root), e.g.
#   sudo ./scripts/demo-blockage.sh
#
# Options:
#   PRUNE=1 ./scripts/demo-blockage.sh      # also remove docker image on exit
#
# Ctrl+C to stop. Generated profile and binaries are cleaned up on exit.

set -euo pipefail

# Run from the repository root regardless of where the script is invoked.
cd "$(dirname "$0")/.."

usage() {
  sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
}

TUI_FLAG=""
USE_REAL=""
REPORT_FILE=""

while [[ "${1:-}" == --* ]]; do
  case "$1" in
    --help|-h) usage; exit 0 ;;
    --tui)  TUI_FLAG="--tui"; shift ;;
    --real) USE_REAL="1"; shift ;;
    --report)
      if [[ -z "${2:-}" || "${2:-}" == --* ]]; then
        echo "error: --report requires a filename" >&2
        exit 1
      fi
      REPORT_FILE="$2"
      shift 2
      ;;
    *) echo "error: unknown flag: $1" >&2; usage >&2; exit 1 ;;
  esac
done

REAL_PROFILE="testdata/profiles/geo_blockage.yaml"
# Generated fast profile lives under testdata/profiles/ so the macOS Docker
# proxy bind-mounts it the same way as any committed profile.
FAST_PROFILE="testdata/profiles/.geo_blockage_demo.yaml"

if [[ -n "$USE_REAL" ]]; then
  PROFILE_PATH="$REAL_PROFILE"
else
  PROFILE_PATH="$FAST_PROFILE"
fi

cleanup() {
  echo ""
  echo "cleaning up..."
  docker ps -q --filter "ancestor=ntnbox:latest" | while read -r cid; do docker stop "$cid" 2>/dev/null; done || true
  rm -f ntnbox poller "$FAST_PROFILE"
  if [[ "${PRUNE:-}" == "1" ]]; then
    echo "pruning docker image..."
    docker rmi ntnbox:latest 2>/dev/null || true
  fi
  echo "done."
}
trap cleanup EXIT

# Write the short demo profile (skipped for --real).
if [[ -z "$USE_REAL" ]]; then
  cat > "$FAST_PROFILE" <<'YAML'
name: geo_blockage_demo
description: >
  Short demo variant of geo_blockage for a fast local loop. Same GEO link
  values, but a 30s cycle with early blockages so drops appear within ~10s.
  Generated by scripts/demo-blockage.sh; not a committed profile.
schedule:
  mode: continuous
  period_sec: 30
  lookahead_sec: 0
blockages:
  - { offset_sec: 10, duration_sec: 4 }   # short tunnel
  - { offset_sec: 20, duration_sec: 6 }   # tree-lined ridge
curves:
  delay_ms:
    - { offset_sec: 0, value: 600 }
  jitter_ms:
    - { offset_sec: 0, value: 15 }
  loss_pct:
    - { offset_sec: 0, value: 0.5 }
  bandwidth_kbps:
    - { offset_sec: 0, value: 20000 }
YAML
fi

echo "==> building ntnbox + poller..."
go build -o ntnbox ./cmd/ntnbox/
go build -o poller ./cmd/poller/

echo "==> building docker image (macOS runs ntnbox inside Docker)..."
docker build -t ntnbox:latest . -q

# Poll an external host so the request traverses the SHAPED veth path.
# Do NOT target the veth gateway (10.200.0.1) or ntnbox's own API/echo: that
# address is the netem control-exempt IP (kept reachable during 100% loss so
# the control/SSE plane survives an outage), so polling it would succeed even
# during a blockage and the demo would show no drops. Using an external URL,
# the poll succeeds while covered and fails (timeout) during a blockage.
#
# A blockage can also surface as a DNS error rather than a clean timeout
# (name resolution needs the link too); either way it is a visible failure.
# Override with TARGET_URL, e.g. TARGET_URL=http://1.1.1.1 to skip DNS.
TARGET_URL="${TARGET_URL:-http://example.com}"

# macOS bash 3.2 + set -u rejects "${empty_array[@]}" — build argv explicitly.
RUN_ARGV=(run)
if [[ -n "$TUI_FLAG" ]]; then RUN_ARGV+=(--tui); fi
if [[ -n "$REPORT_FILE" ]]; then RUN_ARGV+=(--report "$REPORT_FILE"); fi
RUN_ARGV+=(--addr "127.0.0.1:8080" --profile "$PROFILE_PATH" -- poller --url "$TARGET_URL" --interval 1s)

cat <<INFO

==> scenario: continuously-covered GEO link with unscheduled blockage
    profile: $PROFILE_PATH
    target:  $TARGET_URL  (traverses the shaped link)
    watch for: steady 200s, then sudden "timeout" rows during a blockage
               (tunnel / ridge), then recovery — with NO advance warning.
    GUI available at: http://localhost:8080/ui
INFO
if [[ -n "$REPORT_FILE" ]]; then
  echo "    report → $REPORT_FILE (written when you stop the demo)"
fi
cat <<INFO

INFO

./ntnbox "${RUN_ARGV[@]}"
